version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/devdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
